language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t korotky/docker-react . 

script:
  - docker run -e CI=true korotky/docker-react npm run test -- --coverage